spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      # id唯一标志
      - id: consumer-service-route
        # 路由服务地址
        # uri: http://127.0.0.1:8081
        # 采用lb协议, 会从Eureka注册中心获取服务请求地址
        # 路由地址如果通过lb协议加服务名称时, 会自动使用负载均衡访问对应服务
        # 规则: lb协议 + 服务名称
        uri: http://127.0.0.1:8081
        # 断言
        predicates:
        - Path=/**


eureka:
  client:
    service-url:
      default: http://127.0.0.1:8761/eureka
server:
  port: 10010