server:
  port: 9091

spring:
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456


# 指定向哪台 eureka服务端注册
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
  instance:
    # 是否显示ip地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
