
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:cn.itcast.springboot_mybatis_mvc.mapper.GetdataMapper/*.xml
server:
  port: 8090