server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      #  将当前注册中心的数据 同步给集群中另一台eureka中心
      defaultZone: http://localhost:8761/eureka
    # 是否将自己注册到 注册中心, 默认 开启
    register-with-eureka: true
    # 是否拉取注册中心的服务提供者列表, 默认 开启
    fetch-registry: true

