server:
  port: 8081

spring:
  application:
    name: user-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka1:8761/eureka
  instance:
    # 是否显示ip地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port


# 配置熔断策略：
hystrix:
  command:
    default:
      circuitBreaker:
        forceOpen: false # 强制打开熔断器 默认false关闭的
        errorThresholdPercentage: 10 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 5000  # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 6  # 熔断触发最小请求次数，默认值是20
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  # 熔断超时设置，默认为1秒










