server:
  port: 10010

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: item-consumer-route
        uri: lb://item-consumer
        predicates:
        - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
