server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

spring:
  application:
    name: item-provider
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
